# 我是第一个配置文件
server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:suojunchao/springcloud-config.git # GitHub上面的Git仓库名字
          uri: https://github.com/suojunchao/springcloud-config.git # GitHub上面的Git仓库名字
          search-paths:
        # 搜索目录
            - springcloud-config
          force-pull: true
          username: suo15533040791@163.com
          password: sjc19991106
      # 读取分支
      label: main

# 服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
